### ISSUE TITLE
Xception has differing dimensions than the pretrained model

### ISSUE THREAD

**Issue by samjenks** [Cadene/pretrained-models.pytorch#53]
Hey, when I try to load the pretrained xception model with imagenet, 
`pretrained_model = xception(pretrained='imagenet')`
I encounter this bug:

`RuntimeError: While copying the parameter named block1.rep.0.conv1.weight, whose dimensions in the model are torch.Size([64, 1, 3, 3]) and whose dimensions in the checkpoint are torch.Size([64, 3, 3]).`

It's a bit weird, any idea how to fix it?

**Comment by Cadene** [comment]
@samjenks It should now work https://github.com/Cadene/pretrained-models.pytorch/commit/1efab2f40586e6a3b8316eadcfd94c66466f440e. Please could you confirm?

```
pip install --upgrade pretrainedmodels
```

**Comment by yxchng** [comment]
@Cadene I am still facing the same problem @samjenks Have you solved it?

**Comment by Cadene** [comment]
Fixed
